### ISSUE TITLE
我有几乎完成的efi，实际可以看你去优化

### ISSUE THREAD

**Issue by Eaxyx** [worship76/dell7559_Hackintosh_Monterey#1]

**Comment by Eaxyx** [comment]
需要可以联系我

**Comment by worship-dog** [comment]
目前对我来说影响正常使用的问题有两个，插电池不能开机，hdmi接口不能使用

**Comment by Eaxyx** [comment]
实际上是遇见了重启掉引导的问题，其他基本完美

**Comment by Eaxyx** [comment]
HDMI有些是连接到独显上

**Comment by worship-dog** [comment]
我已经验证过了， 我的HDMI是连接到核显的

**Comment by Eaxyx** [comment]
加qq群895510950，给efi，最基本的，期待有缘人优化




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "worship76/dell7559_Hackintosh_BigSur"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月21日(星期一) 中午11:27
收件人:&nbsp;"worship76/dell7559_Hackintosh_BigSur"<dell7559_Hackintosh_BigSur@noreply.github.com&gt;;
抄送:&nbsp;"墨"<824546092@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [worship76/dell7559_Hackintosh_BigSur] 我有几乎完成的efi，实际可以看你去优化 (#1)





 
我已经验证过了， 我的HDMI是连接到核显的

**Comment by hongxuanzheng** [comment]
> 目前对我来说影响正常使用的问题有两个，插电池不能开机，hdmi接口不能使用

![Uploading 9B9595D3-0BB8-4650-AE53-2BD0DC08D88E.png…]()

**Comment by hongxuanzheng** [comment]
> 需要可以联系我

有没有支持i7-6700hq的Big Sur的efi

**Comment by sawyouintheheaven** [comment]
> 目前对我来说影响正常使用的问题有两个，插电池不能开机，hdmi接口不能使用

所以每次开机是拔掉电池排线，然后插电开机再上电池排线吗？

**Comment by hongxuanzheng** [comment]
@sawyouintheheaven 我的也是戴尔7559，之前也发生插电池不开机卡代码，后来降级bios1.2.2和设置bios后就一切正常了，我想问你现在的bios版本和bios设置怎么样

**Comment by hongxuanzheng** [comment]
@sawyouintheheaven 就是不插充电器会在启动后会经常卡在start initdevice tree 这里，插电源适配器后就开机两次才能引导进系统

**Comment by sawyouintheheaven** [comment]
> @sawyouintheheaven 就是不插充电器会在启动后会经常卡在start initdevice tree 这里，插电源适配器后就开机两次才能引导进系统

我是和楼主一样的i5版本。7559这个机器我折腾了很多次，感觉bios特别玄学。之前我是使用clover的[legacy模式正常使用](https://www.cnblogs.com/katachi/p/12147613.html)的，只是开机慢，不用拔电池排线。功能一切都正常，后来折腾触控板驱动，不知道怎么骚操作clover再也不能引导了，它不识别我的分区。
之后买了白果。

**Comment by worship76** [comment]
> ？

我目前就只一直断开电池排线使用了，，

**Comment by worship-dog** [comment]
@sawyouintheheaven  回复：所以每次开机是拔掉电池排线，然后插电开机再上电池排线吗？
我目前是一直保持电池排线断开的，当台式机用了 
Bios确实玄学，据说使用出厂版本1.0.1的话会少很多问题，可是我的电脑退回bios后会花屏

**Comment by SereinQH** [comment]
> > 需要可以联系我
> 
> 有没有支持i7-6700hq的Big Sur的efi

我的就支持i7-6700hq的Big Sur的efi
