### ISSUE TITLE
black screen on pc but works on hdmi

### ISSUE THREAD

**Issue by FabriSC** [worship76/dell7559_Hackintosh_Monterey#10]
.

**Comment by FabriSC** [comment]
![IMG_20220903_201335](https://user-images.githubusercontent.com/102399203/188292942-9f3f3d27-80d0-4eaf-864c-613ab5c8f410.jpg)
![IMG_20220903_201325](https://user-images.githubusercontent.com/102399203/188292952-aa478c8d-8fac-4d0b-b1be-e2c59e849358.jpg)

**Comment by stop-bullshit** [comment]
did you solve this problem
