### ISSUE TITLE
改新机型可以开hdimi，给别人安装启动黑屏

### ISSUE THREAD

**Issue by xiaoleGun** [worship76/dell7559_Hackintosh_Monterey#2]
首先hdmi是可以用的改完机型，需要在nvram加入agdpmod=vit9696，这是忽略机型的参数。然后在我朋友的机子安装启动黑屏请问哪的问题

**Comment by worship-dog** [comment]
可能是因为没有断开电池排线

**Comment by xiaoleGun** [comment]
是的，已经完善好了

**Comment by worship-dog** [comment]
试着把bios回退到1.0.1也许能解决这个问题

**Comment by xiaoleGun** [comment]
回退没用还会导致闪屏，应该是生产批次问题

**Comment by worship-dog** [comment]
我也是这样  闪屏花屏太离谱了  目前只能保持断开电池排线了

**Comment by xiaoleGun** [comment]
是啊，但幸亏是朋友的机子

**Comment by worship-dog** [comment]
哈哈哈哈哈哈

**Comment by worship-dog** [comment]
新年快乐！

**Comment by xiaoMGitHub** [comment]
感谢指点，在legacy模式下，用OC 0.6.6引导完美

**Comment by worship-dog** [comment]
i5版本的吗  电池有没有问题呢

**Comment by xiaoMGitHub** [comment]
电池显示正常，应该是没问题

**Comment by worship-dog** [comment]
你有没有遇到引导界面不能使用键盘的情况呢



---原始邮件---
发件人: "xiaoMGitHub"<notifications@github.com&gt;
发送时间: 2021年2月19日(周五) 下午5:58
收件人: "worship76/dell7559_Hackintosh_BigSur"<dell7559_Hackintosh_BigSur@noreply.github.com&gt;;
抄送: "worship76"<2655902068@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [worship76/dell7559_Hackintosh_BigSur] 改新机型可以开hdimi，给别人安装启动黑屏 (#2)




 
电池显示正常，应该是没问题

**Comment by xiaoMGitHub** [comment]
目前一切正常，我用了OC的模拟UEFI引导

**Comment by worship-dog** [comment]
我也尝试了legacy安装，可是在引导界面 键盘不能使用，无法选择进入苹果系统



---原始邮件---
发件人: "xiaoMGitHub"<notifications@github.com&gt;
发送时间: 2021年2月19日(周五) 晚上9:11
收件人: "worship76/dell7559_Hackintosh_BigSur"<dell7559_Hackintosh_BigSur@noreply.github.com&gt;;
抄送: "worship76"<2655902068@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [worship76/dell7559_Hackintosh_BigSur] 改新机型可以开hdimi，给别人安装启动黑屏 (#2)




 
目前一切正常，我用了OC的模拟UEFI引导

**Comment by xiaoMGitHub** [comment]
你可以尝试添加 Ps2KeyboardDxe.efi 驱动，我没加这个引导界面能正常使用，你可以试试OC 0.6.6模拟UEFI引导

**Comment by worship-dog** [comment]
好的，感谢



---原始邮件---
发件人: "xiaoMGitHub"<notifications@github.com&gt;
发送时间: 2021年2月19日(周五) 晚上11:22
收件人: "worship76/dell7559_Hackintosh_BigSur"<dell7559_Hackintosh_BigSur@noreply.github.com&gt;;
抄送: "worship76"<2655902068@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [worship76/dell7559_Hackintosh_BigSur] 改新机型可以开hdimi，给别人安装启动黑屏 (#2)




 
你可以尝试添加 Ps2KeyboardDxe.efi 驱动，我没加这个引导界面能正常使用，你可以试试OC 0.6.6模拟UEFI引导

**Comment by worship-dog** [comment]
> 你可以尝试添加 Ps2KeyboardDxe.efi 驱动，我没加这个引导界面能正常使用，你可以试试OC 0.6.6模拟UEFI引导

老哥  能给我一份你的EFI吗

**Comment by worship-dog** [comment]
> 你可以尝试添加 Ps2KeyboardDxe.efi 驱动，我没加这个引导界面能正常使用，你可以试试OC 0.6.6模拟UEFI引导

我尝试了模拟UEFI引导，但是遇到了 键盘不能使用的问题，几经查访发现 是drivers的问题，更换了正确的efi文件之后，仍然无法使用键盘，经过测试 ，确定是由于 新的引导没有生效，比如我在设置里隐藏了辅助条目，等待时间设置5s，可是实际启动时辅助条目仍然在，等待时间也没有变化。 值得注意的地方是 在进入模拟UEFI引导界面前，会显示BOOT MISMATCH，请问你知道是怎么回事吗

**Comment by xiaoMGitHub** [comment]
你的LegacyBoot写入工具应该是有问题，打开BootInstallBase.sh脚本，在开头#!/bin/bash后面加上ARCHS=X64

**Comment by worship-dog** [comment]
感谢回复！明天我就尝试一下



---原始邮件---
发件人: "xiaoMGitHub"<notifications@github.com&gt;
发送时间: 2021年2月23日(周二) 晚上9:38
收件人: "worship76/dell7559_Hackintosh_BigSur"<dell7559_Hackintosh_BigSur@noreply.github.com&gt;;
抄送: "worship76"<2655902068@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [worship76/dell7559_Hackintosh_BigSur] 改新机型可以开hdimi，给别人安装启动黑屏 (#2)




 
你的LegacyBoot写入工具应该是有问题，打开BootInstallBase.sh脚本，在开头#!/bin/bash后面加上ARCHS=X64

**Comment by worship-dog** [comment]
试过之后，还是无效，感觉像是第一次的引导产生了缓存，bios每次都从缓存加载引导，打算直接重装了



---原始邮件---
发件人: "xiaoMGitHub"<notifications@github.com&gt;
发送时间: 2021年2月23日(周二) 晚上9:38
收件人: "worship76/dell7559_Hackintosh_BigSur"<dell7559_Hackintosh_BigSur@noreply.github.com&gt;;
抄送: "worship76"<2655902068@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [worship76/dell7559_Hackintosh_BigSur] 改新机型可以开hdimi，给别人安装启动黑屏 (#2)




 
你的LegacyBoot写入工具应该是有问题，打开BootInstallBase.sh脚本，在开头#!/bin/bash后面加上ARCHS=X64

**Comment by xiaoMGitHub** [comment]
你写入mbr引导的日志贴出来看看

**Comment by xiaoleGun** [comment]
看了你新更新的引导，信息不能用得打apple客服洗白，就唠唠嗑，一直缠着他，说我的电脑不能用.....预估你的电脑会有一个错误代码，给他让他重置一下apple id（有可能他自己会说，一开始代码给他就行，一定要主动给）重置就相当于洗白你的序列号，保留好它，以后都有大用

**Comment by worship-dog** [comment]
电脑在公司&nbsp; &nbsp;我明天贴出来！谢谢大佬



---原始邮件---
发件人: "xiaoMGitHub"<notifications@github.com&gt;
发送时间: 2021年2月25日(周四) 下午5:00
收件人: "worship76/dell7559_Hackintosh_BigSur"<dell7559_Hackintosh_BigSur@noreply.github.com&gt;;
抄送: "worship76"<2655902068@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [worship76/dell7559_Hackintosh_BigSur] 改新机型可以开hdimi，给别人安装启动黑屏 (#2)




 
你写入mbr引导的日志贴出来看看

**Comment by worship-dog** [comment]
卧槽还能这么搞吗&nbsp;



---原始邮件---
发件人: "xiaoleGun"<notifications@github.com&gt;
发送时间: 2021年2月25日(周四) 下午5:06
收件人: "worship76/dell7559_Hackintosh_BigSur"<dell7559_Hackintosh_BigSur@noreply.github.com&gt;;
抄送: "worship76"<2655902068@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [worship76/dell7559_Hackintosh_BigSur] 改新机型可以开hdimi，给别人安装启动黑屏 (#2)




 
看了你新更新的引导，信息不能用得打apple客服洗白，就唠唠嗑，一直缠着他，说我的电脑不能用.....预估你的电脑会有一个错误代码，给他让他重置一下apple id（有可能他自己会说，一开始代码给他就行，一定要主动给）重置就相当于洗白你的序列号，保留好它，以后都有大用

**Comment by xiaoleGun** [comment]
> 卧槽还能这么搞吗&nbsp;
> […](#)
对啊，所以想用就去洗白一下，我懒得洗了，麻烦死了

**Comment by worship-dog** [comment]
哈哈哈&nbsp; 我也懒得弄



---原始邮件---
发件人: "xiaoleGun"<notifications@github.com&gt;
发送时间: 2021年2月25日(周四) 晚上7:42
收件人: "worship76/dell7559_Hackintosh_BigSur"<dell7559_Hackintosh_BigSur@noreply.github.com&gt;;
抄送: "worship76"<2655902068@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [worship76/dell7559_Hackintosh_BigSur] 改新机型可以开hdimi，给别人安装启动黑屏 (#2)




  
卧槽还能这么搞吗&nbsp;
 …
 对啊，所以想用就去洗白一下，我懒得洗了，麻烦死了

**Comment by worship-dog** [comment]
> 你写入mbr引导的日志贴出来看看

![iShot2021-02-26 09 05 11](https://user-images.githubusercontent.com/50063740/109240256-2034ae80-7812-11eb-9cf4-d2287f9d0a49.png)
![iShot2021-02-26 09 05 53](https://user-images.githubusercontent.com/50063740/109240261-21fe7200-7812-11eb-864e-cc42d3c7f8d1.png)
大佬你看看

**Comment by xiaoMGitHub** [comment]
写入引导没啥问题，应该是你的EFI有问题

**Comment by worship-dog** [comment]
嗯。。能给我一份你用的吗



---原始邮件---
发件人: "xiaoMGitHub"<notifications@github.com&gt;
发送时间: 2021年2月26日(周五) 中午12:21
收件人: "worship76/dell7559_Hackintosh_BigSur"<dell7559_Hackintosh_BigSur@noreply.github.com&gt;;
抄送: "worship76"<2655902068@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [worship76/dell7559_Hackintosh_BigSur] 改新机型可以开hdimi，给别人安装启动黑屏 (#2)




 
写入引导没啥问题，应该是你的EFI有问题
