### ISSUE TITLE
LegacyBoot引导模式安装Bigsur

### ISSUE THREAD

**Issue by xiaoMGitHub** [worship76/dell7559_Hackintosh_Monterey#3]
当开个新帖吧，文件我传上来，我没有这个机器前段时间帮机友装的，他也没反馈有什么问题，当个测试，有问题及时反馈
[EFI_Dell_7559_0.6.6.zip](https://github.com/worship76/dell7559_Hackintosh_BigSur/files/6049826/EFI_Dell_7559_0.6.6.zip)
[LegacyBoot.zip](https://github.com/worship76/dell7559_Hackintosh_BigSur/files/6049827/LegacyBoot.zip)

**Comment by worship-dog** [comment]
感谢大佬&nbsp; 一定及时反馈



---原始邮件---
发件人: "xiaoMGitHub"<notifications@github.com&gt;
发送时间: 2021年2月26日(周五) 晚上9:14
收件人: "worship76/dell7559_Hackintosh_BigSur"<dell7559_Hackintosh_BigSur@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [worship76/dell7559_Hackintosh_BigSur] LegacyBoot引导模式安装Bigsur (#3)




 
当开个新帖吧，文件我传上来，我没有这个机器前段时间帮机友装的，他也没反馈有什么问题，当个测试，有问题及时反馈
 EFI_Dell_7559_0.6.6.zip
 LegacyBoot.zip

**Comment by worship-dog** [comment]
EFI没有问题，uefi引导正常进入系统使用，但是制作legacyboot后 显示boot mismatch&nbsp; 和boot fail，不能进入引导界面



---原始邮件---
发件人: "xiaoMGitHub"<notifications@github.com&gt;
发送时间: 2021年2月26日(周五) 晚上9:14
收件人: "worship76/dell7559_Hackintosh_BigSur"<dell7559_Hackintosh_BigSur@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [worship76/dell7559_Hackintosh_BigSur] LegacyBoot引导模式安装Bigsur (#3)




 
当开个新帖吧，文件我传上来，我没有这个机器前段时间帮机友装的，他也没反馈有什么问题，当个测试，有问题及时反馈
 EFI_Dell_7559_0.6.6.zip
 LegacyBoot.zip

**Comment by xiaoMGitHub** [comment]
使用最新的BIOS，找个U盘新建一个ESP分区，写入MBR引导信息，把EFI丢进去试试

**Comment by worship-dog** [comment]
嗯嗯我试一下



---原始邮件---
发件人: "xiaoMGitHub"<notifications@github.com&gt;
发送时间: 2021年2月27日(周六) 下午4:58
收件人: "worship76/dell7559_Hackintosh_BigSur"<dell7559_Hackintosh_BigSur@noreply.github.com&gt;;
抄送: "worship76"<2655902068@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [worship76/dell7559_Hackintosh_BigSur] LegacyBoot引导模式安装Bigsur (#3)




 
使用最新的BIOS，找个U盘新建一个ESP分区，写入MBR引导信息，把EFI丢进去试试

**Comment by worship-dog** [comment]
我试试重建一下MBR



---原始邮件---
发件人: "xiaoMGitHub"<notifications@github.com&gt;
发送时间: 2021年2月27日(周六) 下午4:58
收件人: "worship76/dell7559_Hackintosh_BigSur"<dell7559_Hackintosh_BigSur@noreply.github.com&gt;;
抄送: "worship76"<2655902068@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [worship76/dell7559_Hackintosh_BigSur] LegacyBoot引导模式安装Bigsur (#3)




 
使用最新的BIOS，找个U盘新建一个ESP分区，写入MBR引导信息，把EFI丢进去试试

**Comment by worship-dog** [comment]
emm还是不行，更离谱的是，我不在u盘里放EFI，只有一个boot文件，还能进入之前的oc引导界面



---原始邮件---
发件人: "xiaoMGitHub"<notifications@github.com&gt;
发送时间: 2021年2月27日(周六) 下午4:58
收件人: "worship76/dell7559_Hackintosh_BigSur"<dell7559_Hackintosh_BigSur@noreply.github.com&gt;;
抄送: "worship76"<2655902068@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [worship76/dell7559_Hackintosh_BigSur] LegacyBoot引导模式安装Bigsur (#3)




 
使用最新的BIOS，找个U盘新建一个ESP分区，写入MBR引导信息，把EFI丢进去试试

**Comment by xiaoMGitHub** [comment]
我简单说下怎么操作： 
* 更新最新 BIOS  
* 修改 BIOS 引导模式为 legacy 模式  
* 找个U盘，新建一个ESP分区
* 找台Mac，使用 legacyboot.zip 中的 BootInstallBase.sh 脚本向U盘中的 ESP 分区写入MBR引导信息  
* 将 EFI 替换到 ESP 分区
* 重启进行引导

**Comment by worship-dog** [comment]
重复很多次&nbsp; 还是没起作用。。我放弃了&nbsp; 辛苦大佬



---原始邮件---
发件人: "xiaoMGitHub"<notifications@github.com&gt;
发送时间: 2021年2月27日(周六) 晚上7:58
收件人: "worship76/dell7559_Hackintosh_BigSur"<dell7559_Hackintosh_BigSur@noreply.github.com&gt;;
抄送: "worship76"<2655902068@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [worship76/dell7559_Hackintosh_BigSur] LegacyBoot引导模式安装Bigsur (#3)




 
我简单说下怎么操作：
  
更新最新 BIOS 

修改 BIOS 引导模式为 legacy 模式 

找个U盘，新建一个ESP分区 

找台Mac，使用 legacyboot.zip 中的 BootInstallBase.sh 脚本向U盘中的 ESP 分区写入MBR引导信息 

将 EFI 替换到 ESP 分区 

重启进行引导

**Comment by xiaoMGitHub** [comment]
难搞，我一次就成功了

**Comment by worship-dog** [comment]
唉&nbsp; 你的cpu是i5-6300吗



---原始邮件---
发件人: "xiaoMGitHub"<notifications@github.com&gt;
发送时间: 2021年2月27日(周六) 晚上11:48
收件人: "worship76/dell7559_Hackintosh_BigSur"<dell7559_Hackintosh_BigSur@noreply.github.com&gt;;
抄送: "worship76"<2655902068@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [worship76/dell7559_Hackintosh_BigSur] LegacyBoot引导模式安装Bigsur (#3)




 
难搞，我一次就成功了

**Comment by worship-dog** [comment]
我可不可以直接用你的boot呢



---原始邮件---
发件人: "xiaoMGitHub"<notifications@github.com&gt;
发送时间: 2021年2月27日(周六) 晚上11:48
收件人: "worship76/dell7559_Hackintosh_BigSur"<dell7559_Hackintosh_BigSur@noreply.github.com&gt;;
抄送: "worship76"<2655902068@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [worship76/dell7559_Hackintosh_BigSur] LegacyBoot引导模式安装Bigsur (#3)




 
难搞，我一次就成功了

**Comment by xiaoMGitHub** [comment]
你没有完整使用我提供的EFI？

**Comment by worship-dog** [comment]
用了呀&nbsp; 没有改动的



---原始邮件---
发件人: "xiaoMGitHub"<notifications@github.com&gt;
发送时间: 2021年2月28日(周日) 凌晨0:07
收件人: "worship76/dell7559_Hackintosh_BigSur"<dell7559_Hackintosh_BigSur@noreply.github.com&gt;;
抄送: "worship76"<2655902068@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [worship76/dell7559_Hackintosh_BigSur] LegacyBoot引导模式安装Bigsur (#3)




 
你没有完整使用我提供的EFI？

**Comment by worship-dog** [comment]
我的意思是&nbsp; &nbsp;那个boot文件，应该要是通用的吧



---原始邮件---
发件人: "xiaoMGitHub"<notifications@github.com&gt;
发送时间: 2021年2月28日(周日) 凌晨0:07
收件人: "worship76/dell7559_Hackintosh_BigSur"<dell7559_Hackintosh_BigSur@noreply.github.com&gt;;
抄送: "worship76"<2655902068@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [worship76/dell7559_Hackintosh_BigSur] LegacyBoot引导模式安装Bigsur (#3)




 
你没有完整使用我提供的EFI？

**Comment by xiaoMGitHub** [comment]
那个是OC 0.6.6安装包里面提供的，是通用的，我觉得还是操作问题，我特意咨询了之前帮忙安装的机友，确实是没问题

**Comment by worship-dog** [comment]
可能那个机友直接用了uefi启动吧。



---原始邮件---
发件人: "xiaoMGitHub"<notifications@github.com&gt;
发送时间: 2021年2月28日(周日) 中午11:00
收件人: "worship76/dell7559_Hackintosh_BigSur"<dell7559_Hackintosh_BigSur@noreply.github.com&gt;;
抄送: "worship76"<2655902068@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [worship76/dell7559_Hackintosh_BigSur] LegacyBoot引导模式安装Bigsur (#3)




 
那个是OC 0.6.6安装包里面提供的，是通用的，我觉得还是操作问题，我特意咨询了之前帮忙安装的机友，确实是没问题

**Comment by xiaoMGitHub** [comment]
我亲手为他安装的，全套都是我操作，可以确定不是UEFI引导

**Comment by worship-dog** [comment]
我现在在试最后一次，，我跟你说一下我的整个流程吧



---原始邮件---
发件人: "xiaoMGitHub"<notifications@github.com&gt;
发送时间: 2021年2月28日(周日) 中午11:07
收件人: "worship76/dell7559_Hackintosh_BigSur"<dell7559_Hackintosh_BigSur@noreply.github.com&gt;;
抄送: "worship76"<2655902068@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [worship76/dell7559_Hackintosh_BigSur] LegacyBoot引导模式安装Bigsur (#3)




 
我亲手为他安装的，全套都是我操作，可以确定不是UEFI引导

**Comment by worship-dog** [comment]
1.windows下制作windows启动盘
2.windows启动盘启动，删除机械、固态所有分区，新建机械硬盘分区，安装windows
3.进入windows系统，制作macos安装盘
4.uefi下&nbsp; oc引导安装黑苹果到固态硬盘
5.进入黑苹果&nbsp; 磁盘工具 抹掉另一个U盘 分区格式为GUID&nbsp;
6.打开终端&nbsp; sudo bootinstallbase.sh选择刚刚抹掉的U盘
7.拖入EFI文件夹
8.重启按F2进入BIOS，修改为legacy引导模式
9.F12，选择legacy下U盘启动



---原始邮件---
发件人: "xiaoMGitHub"<notifications@github.com&gt;
发送时间: 2021年2月28日(周日) 中午11:07
收件人: "worship76/dell7559_Hackintosh_BigSur"<dell7559_Hackintosh_BigSur@noreply.github.com&gt;;
抄送: "worship76"<2655902068@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [worship76/dell7559_Hackintosh_BigSur] LegacyBoot引导模式安装Bigsur (#3)




 
我亲手为他安装的，全套都是我操作，可以确定不是UEFI引导
