### ISSUE TITLE
USB定制+蓝牙的问题

### ISSUE THREAD

**Issue by royccg** [worship76/dell7559_Hackintosh_Monterey#5]
大神，您好。
我的版本跟你一样，oc下也能monterey正常开机
1、但是 我USB按照网上的教程也定制完了，hackintool上 也正确识别了，单是 访达 和 磁盘工具 上 就是 没有是被出来
![Snipaste_2021-12-19_14-36-04](https://user-images.githubusercontent.com/44716144/146666362-689f59be-330d-4c05-bccd-0eec2fde14d5.png)
2、蓝牙也是 加入了驱动，最小内核也填写了，但是 蓝牙也驱动不成功
![image](https://user-images.githubusercontent.com/44716144/146666377-8edd427d-064c-422f-bda2-08b00be0e204.png)
能给我一下指导吗？谢谢

**Comment by royccg** [comment]
我自己解决了，
1、usb的问题，在定制过程中，把`IOUSBHostDevice`改为 `internal`
![image](https://user-images.githubusercontent.com/44716144/146672039-5a7bddfe-8313-48c1-8313-a7ab252e5093.png)
2、蓝牙的 应该也是 上面那个问题，再加上，注入的 Kext的顺序。
![image](https://user-images.githubusercontent.com/44716144/146672084-2068b117-2f81-4cdb-abc9-61e728dad6f7.png)
![image](https://user-images.githubusercontent.com/44716144/146672129-7d660478-a83c-428a-8593-98e0b963eead.png)
我先在  存在的问题，应该是 ，屏幕亮度不能调节。。。。

**Comment by worship-dog** [comment]
你好，最近工作比较忙，没登录github，也没有收到github的邮件提醒，就一直没看到这个提问，不好意思。
亮度不能调节的话，检查一下**ACPI**中是否有 **SSDT-PNLF.aml**这个补丁，如果没有的话可以加上这个[补丁](https://dortania.github.io/OpenCore-Install-Guide/ktext.html#high-end-desktop)尝试一下，希望能能帮到你。
