### ISSUE TITLE
亮度调节

### ISSUE THREAD

**Issue by LetitbeOK** [worship76/dell7559_Hackintosh_Monterey#6]
您好 
7559 i7 4k
bios:1.2.2
安装好12.0.1后发现亮度调节只能为最大值，只要比最大值小则显示为黑屏，是本身就存在问题，还是我安装的问题呢？

**Comment by worship-dog** [comment]
没有遇到过，我也不清楚问题所在





------------------ 原始邮件 ------------------
发件人: LetitbeOK ***@***.***&gt;
发送时间: 2022年7月2日 14:47
收件人: worship76/dell7559_Hackintosh_Monterey ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [worship76/dell7559_Hackintosh_Monterey] 亮度调节 (Issue #6)





 
您好
 7559 i7 4k
 bios:1.2.2
 安装好12.0.1后发现亮度调节只能为最大值，只要比最大值小则显示为黑屏，是本身就存在问题，还是我安装的问题呢？

**Comment by LetitbeOK** [comment]
好吧 还是感谢您做出回应 我再研究研究😄
