### ISSUE TITLE
Installation on Dell Inspiron 7559 i5-6300HQ.

### ISSUE THREAD

**Issue by Karansidds** [worship76/dell7559_Hackintosh_Monterey#7]
Hey there,

Laptop Specs:
OS: Linux
Processor: i5-6300HQ
RAM: 16 GB
Graphics Card: NVIDIA GeForce GTX 960M

Can you please help me out to install MacOS Monterey on my laptop? I am having a hard time setting up the installer. I tried different methods, but none of them worked out. I am always getting a black screen after picking the installer.

**Comment by worship-dog** [comment]
Hello,
I'd like to help you. But before that, please answer me some questiones.
Which EFI are you using?&nbsp;&nbsp;
Which version of BIOS are you using?&nbsp;
Have you ever tried to disconnect the battery cable?&nbsp;


Waiting for you reply.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "worship76/dell7559_Hackintosh_Monterey"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月15日(星期五) 晚上8:50
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[worship76/dell7559_Hackintosh_Monterey] Installation on Dell Inspiron 7559 i5-6300HQ. (Issue #7)





 
Hey there,
 
Can you please help me out to install MacOS Monterey on my laptop? I am having a hard time setting up the installer. I tried different methods, but none of them worked out. I am always getting a black screen after picking the installer.

**Comment by Karansidds** [comment]
I am using the latest OpenCore EFI (0.8.2). I also tried using your EFI that your posted in this repo.
BIOS Version: 1.3.1
I always keep my battery cable connected to my laptop. My laptop is always charging.

I am waiting for your response.

**Comment by worship-dog** [comment]
Disconnect th battery cable, it is not the battery charger. I mean，remove the battery from your laptop, just use the charger and try again. If it still doesn't work,&nbsp; downgrade the version of BIOS to 1.0.1.


TIPS:
Make sure your bios settings like this
&nbsp;

Advanced
VT for direct I/O —————— Disabled

SATA Operation —————— AHCI

SupportAssist System Resolution —————— OFF


Security
Firmware TPM —————— Disabled


Boot
Boot List Option —————— UEFI

Secure boot —————— Disabled

Load Legacy Option Rom —————— Disabled

keep other options defalut value


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "worship76/dell7559_Hackintosh_Monterey"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月16日(星期六) 中午1:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [worship76/dell7559_Hackintosh_Monterey] Installation on Dell Inspiron 7559 i5-6300HQ. (Issue #7)





 
I am using the latest OpenCore EFI (0.8.2). I also tried using your EFI that your posted in this repo.
 BIOS Version: 1.3.1
 I always keep my battery cable connected to my laptop. My laptop is always charging.
 
I am waiting for your response.

**Comment by Karansidds** [comment]
Do you mean that I should remove the battery from my laptop? If yes, then I would like to know how the battery could affect the installation process?

**Comment by worship-dog** [comment]
I don't known the reason. I just known it is summarized by other predecessors.





------------------ Original ------------------
From: Karan Siddannavar ***@***.***&gt;
Date: Sun,Jul 17,2022 2:18 AM
To: worship76/dell7559_Hackintosh_Monterey ***@***.***&gt;
Cc: worship76 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [worship76/dell7559_Hackintosh_Monterey] Installation on Dell Inspiron 7559 i5-6300HQ. (Issue #7)





 
Do you mean that I should remove the battery from my laptop? If yes, then I would like to know how the battery could affect the installation process?

**Comment by Karansidds** [comment]
Sounds good. Thanks for the info. Can I directly use your EFI? I will use the config_i5plist.

If yes, then do I need to make any changes in your EFI?

**Comment by worship-dog** [comment]
You are welcome.
I'm not sure，everyone will encounter different problems.





------------------ Original ------------------
From: Karan Siddannavar ***@***.***&gt;
Date: Sun,Jul 17,2022 1:07 PM
To: worship76/dell7559_Hackintosh_Monterey ***@***.***&gt;
Cc: worship76 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [worship76/dell7559_Hackintosh_Monterey] Installation on DellInspiron 7559 i5-6300HQ. (Issue #7)





 
Sounds good. Thanks for the info. Can I directly use your EFI? I will use the config_i5plist.
 
If yes, then do I need to make any changes in your EFI?

**Comment by Karansidds** [comment]
Do you know the reason why I am getting a black screen after selecting OPENCORE (dmg) option to install MacOS?

**Comment by worship-dog** [comment]
i don't known your specific situation.Probably because bios version error、bios settings error or battery cable not disconnected.





------------------ Original ------------------
From: Karan Siddannavar ***@***.***&gt;
Date: Sun,Jul 17,2022 2:18 PM
To: worship76/dell7559_Hackintosh_Monterey ***@***.***&gt;
Cc: worship76 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [worship76/dell7559_Hackintosh_Monterey] Installation on DellInspiron 7559 i5-6300HQ. (Issue #7)





 
Do you know the reason why I am getting a black screen after selecting OPENCORE (dmg) option to install MacOS?

**Comment by Karansidds** [comment]
Hey. I am getting this error when I'm trying to install MacOS.
![20220717_183935](https://user-images.githubusercontent.com/39003188/179444625-9f046d01-a835-4391-9287-09ed113fd38d.jpg)

Can you please help me out with this? Waiting for your reply.

**Comment by worship-dog** [comment]
Give me your EFI.





------------------ Original ------------------
From: Karan Siddannavar ***@***.***&gt;
Date: Mon,Jul 18,2022 0:17 PM
To: worship76/dell7559_Hackintosh_Monterey ***@***.***&gt;
Cc: worship76 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [worship76/dell7559_Hackintosh_Monterey] Installation on DellInspiron 7559 i5-6300HQ. (Issue #7)





 
Hey. I am getting this error when I'm trying to install MacOS.
 
 
Can you please help me out with this? Waiting for your reply.

**Comment by Karansidds** [comment]
Sure. Thanks for checking it out.

[EFI](https://easyupload.io/vdlte9)

FYI, I am using Linux. I am not sure if that matters. Just wanted you to know. Anyways, thanks for checking it out.

**Comment by worship-dog** [comment]
How can I download it? I clicked everywhere on the page, but there was no response.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "worship76/dell7559_Hackintosh_Monterey"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月18日(星期一) 中午12:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [worship76/dell7559_Hackintosh_Monterey] Installation on Dell Inspiron 7559 i5-6300HQ. (Issue #7)





 
Sure. Thanks for checking it out.
 
EFI
 
FYI, I am using Linux. I am not sure if that matters. Just wanted you to know. Anyways, thanks for checking it out.

**Comment by Karansidds** [comment]
![image](https://user-images.githubusercontent.com/39003188/179458358-7024959e-7b1e-4e09-8e9e-7fb697bacbcc.png)

You have to click on Download

**Comment by Karansidds** [comment]
Were you able to download it?

**Comment by worship-dog** [comment]
I can't. Do you have any other methods to send it to me? Such as e-mail&nbsp;attachment.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Karan ***@***.***&gt;; 
发送时间: 2022年7月18日(星期一) 下午3:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [worship76/dell7559_Hackintosh_Monterey] Installation on Dell Inspiron 7559 i5-6300HQ. (Issue #7)





 
Were you able to download it?

**Comment by Karansidds** [comment]
Sure. Can you send me your email?

**Comment by worship-dog** [comment]
***@***.***




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Karan ***@***.***&gt;; 
发送时间: 2022年7月18日(星期一) 下午3:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [worship76/dell7559_Hackintosh_Monterey] Installation on Dell Inspiron 7559 i5-6300HQ. (Issue #7)





 
Sure. Can you send me your email?

**Comment by worship-dog** [comment]
2655902068@qq.com

**Comment by Karansidds** [comment]
Can you check your mail and let me know?

**Comment by worship-dog** [comment]
> 

2655902068@qq.com

**Comment by Karansidds** [comment]
I have sent you a mail. Please check it out

**Comment by Karansidds** [comment]
[Google Drive for EFI](https://drive.google.com/file/d/1ZAPwixUWdXZPc98kfRdBfJzF1E9quJIn/view)

**Comment by Karansidds** [comment]
Hey, were you able to find the issue?

**Comment by worship-dog** [comment]
> Hey, were you able to find the issue?

I can't get it from mail. And it is a link from google drive, I don't have a vpn to visit google drive.

**Comment by worship-dog** [comment]
Maybe you can create a repository to upload your EFI. Have you searched the way to fix the 'LoadImage failed -Unsupported'?  Check whether the file named 'EFI/OC/Drivers/HfsPlus.efi'  exists.

**Comment by Karansidds** [comment]
I have uploaded the EFI to a GitHub repo

[Link](https://github.com/Karansidds/hackintosh-dell-inspiron-7559)

**Comment by worship-dog** [comment]
Fine, do you know the version of you opencore efi?

**Comment by Karansidds** [comment]
Yeah. The latest version. 0.8.2

**Comment by worship-dog** [comment]
<karansiddannavar09@gmail.com>
I send a email to this mailbox with a EFI zip，please check it out.

**Comment by Karansidds** [comment]
Sure. I will check it now

**Comment by Karansidds** [comment]
Hey. I am not able to download the file that you sent me.

**Comment by worship-dog** [comment]
http://106.12.119.233:8001/file/update_EFI.zip


How about this link?

**Comment by Karansidds** [comment]
It doesn't work

**Comment by worship-dog** [comment]
dell7559_Hackintosh_Monterey/EFI.zip at master · worship76/dell7559_Hackintosh_Monterey (github.com)


I removed the 'AirportItlwm.kext', you need to copy it to EFI/OC/Kexts.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "worship76/dell7559_Hackintosh_Monterey"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月19日(星期二) 下午2:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [worship76/dell7559_Hackintosh_Monterey] Installation on Dell Inspiron 7559 i5-6300HQ. (Issue #7)





 
It doesn't work

**Comment by Karansidds** [comment]
So I need to remove 'AirportItlwm.kext' from Kexts and do a Normal Snapshot, right?

**Comment by worship-dog** [comment]
If you mean to fix the settings of config.plist, you are right.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Karan ***@***.***&gt;; 
发送时间: 2022年7月19日(星期二) 下午5:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [worship76/dell7559_Hackintosh_Monterey] Installation on Dell Inspiron 7559 i5-6300HQ. (Issue #7)





 
So I need to remove 'AirportItlwm.kext' from Kexts and do a Normal Snapshot, right?

**Comment by Karansidds** [comment]
I tried it. It is still giving me the same error.

**Comment by worship-dog** [comment]
Select the clean/reset nvram, and try again. If it is still not work, change a EFI.



------------------ Original ------------------
From: Karan Siddannavar ***@***.***&gt;
Date: Tue,Jul 19,2022 8:30 PM
To: worship76/dell7559_Hackintosh_Monterey ***@***.***&gt;
Cc: 李彬 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [worship76/dell7559_Hackintosh_Monterey] Installation on Dell Inspiron 7559 i5-6300HQ. (Issue #7)





 
I tried it. It is still giving me the same error.

**Comment by Karansidds** [comment]
I tried clearing NVRAM. I still got the same error.

What do you mean by change EFI?

**Comment by worship-dog** [comment]
install with my EFI



------------------ Original ------------------
From: Karan Siddannavar ***@***.***&gt;
Date: Tue,Jul 19,2022 9:09 PM
To: worship76/dell7559_Hackintosh_Monterey ***@***.***&gt;
Cc: 李彬 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [worship76/dell7559_Hackintosh_Monterey] Installation on DellInspiron 7559 i5-6300HQ. (Issue #7)





 
I tried clearing NVRAM. I still got the same error.
 
What do you mean by change EFI?

**Comment by Karansidds** [comment]
Gotcha. I will try your EFI with config_i5.plist.

**Comment by Karansidds** [comment]
I am getting the same error with your EFI as well

**Comment by worship-dog** [comment]
it is impossible. check your&nbsp;operation, I think you made a mistake. such as the efi not replaced.



------------------ Original ------------------
From: Karan Siddannavar ***@***.***&gt;
Date: Tue,Jul 19,2022 9:40 PM
To: worship76/dell7559_Hackintosh_Monterey ***@***.***&gt;
Cc: 李彬 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [worship76/dell7559_Hackintosh_Monterey] Installation on DellInspiron 7559 i5-6300HQ. (Issue #7)





 
I am getting the same error with your EFI as well

**Comment by Karansidds** [comment]
Hey, do you have any idea about this? I am getting this after clicking on the installer.

![image](https://user-images.githubusercontent.com/39003188/180635794-0386bf5b-30d5-4d87-9596-df8237cf2a23.png)

**Comment by worship-dog** [comment]
i have no idea.





------------------ Original ------------------
From: Karan Siddannavar ***@***.***&gt;
Date: Sun,Jul 24,2022 2:46 PM
To: worship76/dell7559_Hackintosh_Monterey ***@***.***&gt;
Cc: 李彬 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [worship76/dell7559_Hackintosh_Monterey] Installation on DellInspiron 7559 i5-6300HQ. (Issue #7)





 
Hey, do you have any idea about this? I am getting this after clicking on the installer.

**Comment by worship-dog** [comment]
just use the config.plist please





------------------ Original ------------------
From: Karan Siddannavar ***@***.***&gt;
Date: Tue,Jul 19,2022 9:15 PM
To: worship76/dell7559_Hackintosh_Monterey ***@***.***&gt;
Cc: 李彬 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [worship76/dell7559_Hackintosh_Monterey] Installation on DellInspiron 7559 i5-6300HQ. (Issue #7)





 
Gotcha. I will try your EFI with config_i5.plist.

**Comment by worship-dog** [comment]
Where?
Turbo Download or Download?
I don't know where you marked it.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "worship76/dell7559_Hackintosh_Monterey"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月18日(星期一) 下午2:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [worship76/dell7559_Hackintosh_Monterey] Installation on Dell Inspiron 7559 i5-6300HQ. (Issue #7)





 

 
You have to click there..
